/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#include "custom.h"

extern void action_init(void);

void custom_init(void)
{
    dev_attr_init();
    action_init();
}








