/*
 * Copyright (C) 2025 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v1.2.0
 */

#ifndef CUSTOM_CODE
#define CUSTOM_CODE
#ifdef __cplusplus
extern "C" {
#endif

#include <string.h>
#include <stdlib.h>

#include "ui.h"
#include "lvgl_test.h"

#include "def.h"
#include "crc16.h"
#include "protocol.h"


void custom_init(void);

#ifdef __cplusplus
}
#endif
#endif /* CUSTOM_CODE */
